### PR TITLE
Update to SonarQube LTS 6.7

### PR DESCRIPTION
**Pull request by marcphilipp**
This PR contains the necessary changes to make the plugin work with SonarQube 6.7.
All tests pass, but it does not resolve all deprecation warnings.

We've tested the following features and made sure that they work:
- Rules/checks/issues
- Code coverage
- Highlighting

We were not able to successfully test the Duplication checks based on CPD. However,
I'm not sure it worked before, either. Unfortunately, we have not enough time to
continue to work on it. However, merging this PR and releasing the plugin would
allow users to at least use a basic version on SonarQube 6.7.

### CODE REVIEW

**Comment by marcphilipp** [comment]
Looks like there are still merge conflicts. I'll investigate.

**Comment by marcphilipp** [comment]
@kalidasya Ok, I now merged master into this branch, trusting that you merged all conflicts in 
dc8d023 .

**Comment by kalidasya** [comment]
@marcphilipp I think its good enough, thank you for the contribution!

**Comment by marcphilipp** [comment]
@kalidasya Thanks! Can you release the plugin?

**Pull request merged**
